disabled_rules: # rule identifiers to exclude from running
  - line_length
  - identifier_name
  - trailing_whitespace
  - force_cast
  - todo
  - weak_delegate
  - nesting
  - type_body_length
  - opening_brace
  - operator_whitespace
  - file_length
  - statement_position
  - cyclomatic_complexity
  - function_body_length
  - for_where
  - force_try
  - function_parameter_count